version: 0.0
os: ubuntu	
files:	
  - source: /views/index.jade 
    destination: /var/www/views/jade	    
hooks:	
  BeforeInstall:	 
    - location: /scripts/install_dependencies	   
      timeout: 300	     
      runas: root	     
    - location: /scripts/start_server	    
      timeout: 300	     
      runas: root	      
