version: 0.2
 
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - apt-get install -y unzip

  build:
    commands:
      - echo Build started on `date`
      - zip hello.zip views/index.jade
   
artifacts:
  type: 
  files:
    -views/index.jade
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
    - 1.png
    - aws.gif
    - back.jpg
